version: '3'

services:

  codebase:
    build:
      context: .
      dockerfile: codebase/dockerfile-codebase
    tty: true
    volumes:
      - codebase:/usr/src/codebase
    command: pull

  spacemandmm:
    build:
      context: .
      dockerfile: spacemandmm/dockerfile-spacemandmm
    tty: true
    volumes: 
      - spacemandmm:/usr/src/spacemandmm/target/release

  renderbus:
    depends_on:
      - spacemandmm
      - codebase
    build:
      context: .
      dockerfile: render/render-dockerfile
    tty: true
    volumes: 
      - codebase:/usr/src/codebase
      - spacemandmm:/usr/src/spacemandmm/target/release
      - ./output:/output
    command: python app.py

  # serve:
  #   depends_on:
  #     - spacemandmm
  #     - codebase
  #     - renderbus
  #   build:
  #     context: .
  #     dockerfile: serve/serve-dockerfile
  #   tty: true
  #   ports: 
  #     - "8080:8080"
  #   volumes: 
  #     - ./output:/output

volumes:
  codebase:
  spacemandmm: