version: '3'

services:

  codebase:
    build:
      context: .
      dockerfile: codebase/dockerfile-codebase
    volumes:
      - codebase:/usr/src/codebase
    command: pull /usr/src/codebase

  spacemandmm:
    build:
      context: .
      dockerfile: spacemandmm/dockerfile-spacemandmm
    tty: true
    volumes: 
      - spacemandmm:/usr/src/spacemandmm/target/release

  renderbus:
    depends_on:
      - spacemandmm
      - codebase
    build:
      context: .
      dockerfile: render/render-dockerfile
    tty: true
    volumes: 
      - codebase:/usr/src/codebase
      - spacemandmm:/usr/src/spacemandmm/target/release
      - ./output:/output
    command: python app.py

volumes:
  codebase:
  spacemandmm: