FROM rust:latest

WORKDIR /usr/src/spacemandmm
RUN apt-get update && apt-get install -y --no-install-recommends cmake pngcrush git python

RUN git clone https://github.com/SpaceManiac/SpacemanDMM.git .

RUN cargo build -p cli --release 

# Clean apt cache
RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

COPY renderer/render.py render.py
RUN chmod +x render.py

CMD ["/usr/bin/python", "render.py" ]