FROM rust:latest

WORKDIR /usr/src/spacemandmm
RUN apt-get clean && rm -r /var/lib/apt/lists/* && apt-get update && apt-get install -y --no-install-recommends cmake

RUN git clone https://github.com/SpaceManiac/SpacemanDMM.git .

RUN cargo build -p cli --release 

# Clean apt cache
RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

ENTRYPOINT ['target/release/dmm-tools minimap']
CMD ['--help']